"""
One-time setup: derive Polymarket CLOB API credentials from your wallet.

Run once on each new machine:
    python3 setup_credentials.py

Prerequisites:
  - POLYMARKET_PRIVATE_KEY must be set in .env (your Polygon EOA wallet)
  - The wallet must have a small amount of MATIC for any potential on-chain ops
  - Install deps: pip install -r requirements.txt

What this does:
  Calls the Polymarket CLOB API to derive/create a signing key pair
  bound to your wallet address. Credentials are deterministic —
  running this multiple times returns the same values.

Output:
  Appends POLYMARKET_API_KEY, POLYMARKET_API_SECRET, POLYMARKET_PASSPHRASE
  to your .env file. These are safe to persist — they're derived from
  your private key but cannot be used to move funds directly.
"""
import os
import sys
from pathlib import Path

# Load .env manually before importing auth (dotenv may not be installed)
def _load_env(path: str = ".env") -> None:
    if not Path(path).exists():
        return
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            os.environ.setdefault(key.strip(), value.strip())

_load_env()

from execution.auth import build_client


def main() -> None:
    print("\n─── Polymarket CLOB Credential Setup ───\n")

    try:
        client = build_client(require_level2=False)
    except EnvironmentError as e:
        print(f"❌ {e}")
        sys.exit(1)

    print("🔑 Deriving API credentials from wallet...")
    try:
        creds = client.create_or_derive_api_creds()
    except Exception as e:
        print(f"❌ Failed to derive credentials: {e}")
        sys.exit(1)

    api_key = creds.api_key
    api_secret = creds.api_secret
    passphrase = creds.api_passphrase

    print(f"\n✅ Credentials derived successfully")
    print(f"   API Key     : {api_key}")
    print(f"   API Secret  : {api_secret[:8]}{'*' * (len(api_secret) - 8)}")
    print(f"   Passphrase  : {passphrase[:8]}{'*' * (len(passphrase) - 8)}")

    env_path = Path(".env")
    existing = env_path.read_text() if env_path.exists() else ""

    lines_to_add: list[str] = []
    for key_name, value in [
        ("POLYMARKET_API_KEY", api_key),
        ("POLYMARKET_API_SECRET", api_secret),
        ("POLYMARKET_PASSPHRASE", passphrase),
    ]:
        if key_name not in existing:
            lines_to_add.append(f"{key_name}={value}")
        else:
            print(f"   ⚠️  {key_name} already in .env — skipping (delete manually to refresh)")

    if lines_to_add:
        with env_path.open("a") as f:
            f.write("\n# Derived CLOB API credentials (generated by setup_credentials.py)\n")
            for line in lines_to_add:
                f.write(line + "\n")
        print(f"\n✅ Credentials written to .env ({len(lines_to_add)} entries)")
    else:
        print("\n✅ .env already up to date")

    # ── USDC approval ──────────────────────────────────────────────────────
    print("\n─── USDC Approval ───\n")
    print("Polymarket's CTF Exchange contract needs a one-time approval to")
    print("spend USDC from your wallet. Without it, all orders will revert.\n")

    try:
        from py_clob_client.clob_types import BalanceAllowanceParams, AssetType
        params = BalanceAllowanceParams(asset_type=AssetType.COLLATERAL)
        usdc = client.get_balance_allowance(params)

        # Debug: print wallet address and raw response so mismatches are visible
        try:
            from eth_account import Account
            pk = os.environ.get("POLYMARKET_PRIVATE_KEY", "").strip()
            address = Account.from_key(pk).address
            print(f"  Wallet address          : {address}")
        except Exception:
            pass
        print(f"  Raw API response        : {usdc}")

        balance_raw = usdc.get("balance", 0)
        # "allowances" is a dict of {contract_address: amount} — take max across all contracts
        allowances_dict = usdc.get("allowances", {})
        allowance_raw = max((float(v) for v in allowances_dict.values()), default=0) if allowances_dict else 0

        print(f"  USDC balance on Polygon : {balance_raw} USDC")
        print(f"  Current CTF allowance   : {allowance_raw} USDC")

        if float(allowance_raw) < 1.0:
            ans = input("\n  Approve unlimited USDC allowance? (yes/no): ").strip().lower()
            if ans == "yes":
                print("  ⏳ Sending approval transaction on Polygon...")
                resp = client.update_balance_allowance(params)
                print(f"  ✅ Approval confirmed: {resp}")
            else:
                print("  ⚠️  Skipped — you must approve before placing live orders.")
        else:
            print("  ✅ Allowance already set — no action needed.")

    except Exception as e:
        print(f"  ⚠️  Could not check USDC state: {e}")
        print("     Make sure your wallet has MATIC for gas and USDC on Polygon.")

    print("\n─── Next steps ───")
    print("  1. Set SHADOW_MODE=false in .env when ready to go live")
    print("  2. Run: python3 websocket.py")
    print()


if __name__ == "__main__":
    main()
